# roles/cis-services/tasks/main.yml
---
- name: "2.1 - Disable unnecessary services"
  ansible.builtin.service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  loop: "{{ cis_disabled_services }}"
  ignore_errors: yes

- name: "2.2 - Remove unnecessary packages"
  ansible.builtin.package:
    name: "{{ item }}"
    state: absent
  loop:
    - telnet
    - rsh-client
    - talk
    - nis
  ignore_errors: yes
