# roles/cis-network/tasks/main.yml
---
# 3.1 - Disable unused network protocols
- name: "3.1.1 - Disable IPv6 if not needed"
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
  loop:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
  when: cis_disable_ipv6 | default(false) | bool

# 3.2 - Network parameters (host)
- name: "3.2.1 - Disable IP forwarding"
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '0'
    sysctl_set: yes
    state: present
    reload: yes

- name: "3.2.2 - Disable ICMP redirects"
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '0'
    sysctl_set: yes
    state: present
    reload: yes
  loop:
    - net.ipv4.conf.all.send_redirects
    - net.ipv4.conf.default.send_redirects

# 3.3 - Network parameters (host and router)
- name: "3.3.1 - Disable source routed packets"
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '0'
    sysctl_set: yes
    state: present
    reload: yes
  loop:
    - net.ipv4.conf.all.accept_source_route
    - net.ipv4.conf.default.accept_source_route

- name: "3.3.2 - Disable ICMP redirect acceptance"
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '0'
    sysctl_set: yes
    state: present
    reload: yes
  loop:
    - net.ipv4.conf.all.accept_redirects
    - net.ipv4.conf.default.accept_redirects

- name: "3.3.3 - Disable secure ICMP redirect acceptance"
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '0'
    sysctl_set: yes
    state: present
    reload: yes
  loop:
    - net.ipv4.conf.all.secure_redirects
    - net.ipv4.conf.default.secure_redirects

- name: "3.3.4 - Log suspicious packets"
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
  loop:
    - net.ipv4.conf.all.log_martians
    - net.ipv4.conf.default.log_martians

- name: "3.3.5 - Ignore broadcast ICMP requests"
  ansible.posix.sysctl:
    name: net.ipv4.icmp_echo_ignore_broadcasts
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

- name: "3.3.7 - Enable TCP SYN cookies"
  ansible.posix.sysctl:
    name: net.ipv4.tcp_syncookies
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
